### ISSUE TITLE
refresh vagrant build

### ISSUE THREAD

**Issue by makeaweli** [Refresh-Hilo/Refresh-Hilo.github.io#5]
Email from Edward Meehan:

Hey Jason,

Wondering if you got the same error I have been getting, or if maybe a package changed dependency to a different version of Ruby. But I am getting a error during provisioning when installing ruby gem github-pages. Says we need to use version 2.0 or higher of Ruby. Wondering if you had this error and found a work around. Was thinking of just using the provisioning  file I have been using that installs RVM and then Ruby 2.1.3, on a ubuntu 14 instead of 12.

Since migrating to this method I am keeping my local clean of all unnecessary packages, including Jekyll.

**Comment by makeaweli** [comment]
Pull request from fork merged:
https://github.com/Refresh-Hilo/Refresh-Hilo.github.io/pull/6

**Comment by edmeehan** [comment]
Nicely done!
